const routes = module.exports = require('next-routes')()

routes.add('index', '/')
routes.add('wait', '/wait')
routes.add('dashboard', '/dashboard')
routes.add('itim', '/itim')
routes.add('approve', '/approve')
routes.add('verify', '/verify')
routes.add('wipper', '/wipper')
routes.add('assignteam', '/assignteam')
routes.add('register', '/register')
